#!/bin/sh -xeu

if ! type curl; then
curl() {
  for lastArg; do :; done
  wget -O- "$lastArg"
}
fi

URL1='https://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/'
URL2="$(curl -sL "$URL1" | grep -o 'quickjs-static-[^"]*\.apk' | head -n 1)"
URL3="$URL1$URL2"

curl -sL "$URL3" | tar xzv --strip-components 2 usr/bin/qjs.static
mv qjs.static qjs

mv qjs /usr/local/bin/
